# Generated by Django 2.0 on 2018-09-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('nickname', models.CharField(max_length=100)),
                ('rewards', models.IntegerField()),
                ('balance', models.FloatField()),
                ('account_number', models.CharField(max_length=24)),
                ('customer_id', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=24)),
                ('merchant_id', models.CharField(max_length=100)),
                ('payer_id', models.CharField(max_length=24)),
                ('purchase_date', models.DateField()),
                ('amount', models.FloatField()),
                ('status', models.CharField(max_length=25)),
                ('medium', models.FloatField()),
                ('description', models.CharField(max_length=400)),
                ('account', models.ManyToManyField(to='HomePage.Account')),
            ],
        ),
    ]
