# Generated by Django 2.0 on 2018-09-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='address_blank', max_length=4000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='carrier',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
