# Generated by Django 2.0 on 2018-09-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180915_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accountID',
            field=models.CharField(default=1, max_length=24),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
