# Generated by Django 2.0 on 2018-09-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180916_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='accountID',
            field=models.IntegerField(max_length=24),
        ),
    ]
