# Generated by Django 2.0 on 2018-09-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180916_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='accountID',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accountId',
            field=models.CharField(default='1', max_length=24),
            preserve_default=False,
        ),
    ]
