# Generated by Django 2.0 on 2018-09-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180916_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='accountId',
        ),
    ]
