# Generated by Django 2.0 on 2018-09-16 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_userprofile_accountid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accountID',
            field=models.CharField(default='23', max_length=24),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pkTemp',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
