# Generated by Django 2.0 on 2018-09-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180916_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='pkTemp',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
